<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_56a24cf45f9d3',
	'title' => 'Events',
	'fields' => array (
		array (
			'key' => 'field_57606850135b1',
			'label' => 'Schedule',
			'name' => '_copy',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56c72d974711a',
			'label' => 'Repeating Event?',
			'name' => 'repeating_event',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_575ea50d84779',
			'label' => 'Repeating Type',
			'name' => 'repeat',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56c72d974711a',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'fixed' => 'Fixed Pattern (ex: every Monday, or every Thursday and Friday)',
				'random' => 'Non-consecutive days (ex: Monday one week, Wednesday another, Thursday the next)',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_56c7283647119',
			'label' => 'Repeating Days: Fixed Pattern',
			'name' => 'repeating_days',
			'type' => 'checkbox',
			'instructions' => '(Ex. Every Monday, or Every Thursday and Friday)',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_575ea50d84779',
						'operator' => '==',
						'value' => 'fixed',
					),
					array (
						'field' => 'field_56c72d974711a',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Sunday' => 'Sunday',
				'Monday' => 'Monday',
				'Tuesday' => 'Tuesday',
				'Wednesday' => 'Wednesday',
				'Thursday' => 'Thursday',
				'Friday' => 'Friday',
				'Saturday' => 'Saturday',
			),
			'default_value' => array (
			),
			'layout' => 'vertical',
			'toggle' => 0,
		),
		array (
			'key' => 'field_573db1a3299f9',
			'label' => 'Recurring Event: Non-Consecutive Days',
			'name' => 'recurring_event_non-consecutive_days',
			'type' => 'repeater',
			'instructions' => '(ex: Monday one week, Wednesday another, Thursday the next)	Be sure to list out the dates in the description.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_575ea50d84779',
						'operator' => '==',
						'value' => 'random',
					),
					array (
						'field' => 'field_56c72d974711a',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Date',
			'sub_fields' => array (
				array (
					'key' => 'field_575eb024061d4',
					'label' => 'Event Date',
					'name' => 'event_date',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'm/d/Y',
					'return_format' => 'Y-m-d',
					'first_day' => 0,
				),
				array (
					'key' => 'field_575eb09b061d5',
					'label' => 'Event Start Time',
					'name' => 'event_start_time',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'g:i a',
					'return_format' => 'g:i a',
				),
				array (
					'key' => 'field_575eb0d0061d6',
					'label' => 'Event End Time',
					'name' => 'event_end_time',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'g:i a',
					'return_format' => 'g:i a',
				),
			),
		),
		array (
			'key' => 'field_56b0e1f3ee21b',
			'label' => 'Start Date',
			'name' => 'start_date',
			'type' => 'date_picker',
			'instructions' => '(If a repeating event, put the date of first occurrence here)',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'm/d/Y',
			'return_format' => 'Y-m-d',
			'first_day' => 0,
		),
		array (
			'key' => 'field_56b0e211ee21c',
			'label' => 'End Date',
			'name' => 'end_date',
			'type' => 'date_picker',
			'instructions' => '(If a repeating event, put the date of last occurrence here)',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'm/d/Y',
			'return_format' => 'Y-m-d',
			'first_day' => 0,
		),
		array (
			'key' => 'field_56b0e62c4a6e8',
			'label' => 'All Day Event',
			'name' => 'all_day_event',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Check if this is an all-day event.',
			'default_value' => 0,
		),
		array (
			'key' => 'field_56b0e226ee21d',
			'label' => 'Start Time',
			'name' => 'start_time',
			'type' => 'time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56b0e62c4a6e8',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'g:i a',
			'return_format' => 'g:i a',
		),
		array (
			'key' => 'field_56b0e29aee21e',
			'label' => 'End Time',
			'name' => 'end_time',
			'type' => 'time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56b0e62c4a6e8',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'g:i a',
			'return_format' => 'g:i a',
		),
		array (
			'key' => 'field_56c62b30410f1',
			'label' => 'Duration',
			'name' => 'duration',
			'type' => 'number',
			'instructions' => 'Automatically calculated field.	DO NOT CHANGE!',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'admin-hidden',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56d49c30c5822',
			'label' => 'Next Date',
			'name' => 'next_date',
			'type' => 'date_picker',
			'instructions' => 'Automatically calculated field.	DO NOT CHANGE!',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'admin-hidden',
				'id' => '',
			),
			'display_format' => 'm/d/Y',
			'return_format' => 'Y-m-d',
			'first_day' => 0,
		),
		array (
			'key' => 'field_57029a32223db',
			'label' => 'Day of Week',
			'name' => 'day_of_week',
			'type' => 'text',
			'instructions' => 'Automatically calculated field.	DO NOT CHANGE!',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'admin-hidden',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_575ed14cdd87a',
			'label' => 'All Dates',
			'name' => 'all_dates',
			'type' => 'text',
			'instructions' => 'Automatically calculated field.	DO NOT CHANGE!',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'admin-hidden',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5760688c083a5',
			'label' => 'Location',
			'name' => '_copy',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56a24ea8392fc',
			'label' => 'Location Name',
			'name' => 'location_name',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56a24eb5392fd',
			'label' => 'Location Address',
			'name' => 'location_address',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5760682695c46',
			'label' => 'Contact',
			'name' => 'contact',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56a6d9bc2dabe',
			'label' => 'Contact Name',
			'name' => 'contact_name',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56a24e70392fb',
			'label' => 'Contact Email Address',
			'name' => 'contact_email_address',
			'type' => 'email',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_56a24e4e392f9',
			'label' => 'Contact Phone Number',
			'name' => 'contact_phone_number',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56a24e5d392fa',
			'label' => 'Contact Website',
			'name' => 'contact_website',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_576068d599d6c',
			'label' => 'Other',
			'name' => 'other',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56b5209d317fd',
			'label' => 'Featured',
			'name' => 'featured',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_56a6d9ec2dabf',
			'label' => 'Admission Fee',
			'name' => 'admission_fee',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56bc82ea0fbc4',
			'label' => 'Listing URL',
			'name' => 'listing_url',
			'type' => 'text',
			'instructions' => 'Put the relative path of the listing URL here (ex. /listing/2471/The+Round+Barn+Theatre+at+Amish+Acres/ )',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'events',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
?>